# Project Information
site_name: Red Hat OpenShift Service on AWS (ROSA)
site_description: A guided workshop that ranges from application deployment to cluster configuration for ROSA clusters.
site_author: Red Hat

# Nav Menu Definition
nav:
  - Home: index.md
  - Access your lab environment: accessing-the-lab-toolbox-environment.md
  - Part 1 - ROSA cluster deployment:
    - Prerequisites setup: 'rosa-deployment/1-account-setup.md'
    - Deploy the ROSA cluster: 'rosa-deployment/2-deploy.md'
    - Create admin and access: 'rosa-deployment/3-create-admin-and-access.md'
    - Delete the ROSA cluster: 'rosa-deployment/4-delete-cluster.md'
    - Extra - Managing nodes: 'rosa-deployment/extra-1-managing-nodes.md'
    - Extra - Cluster autoscaling: 'rosa-deployment/extra-2-autoscaling.md'
    - Extra - Cluster upgrade: 'rosa-deployment/extra-3-upgrade.md'
  - Part 2 - Application deployment:
    - Deploying hello world app: 'app-deployment/1-deploy-hello-world-using-s2i.md'
    - Deploying sample database: 'app-deployment/2-deploy-sample-db.md'
    - OSToy app overview: 'app-deployment/3-ostoy-lab-overview.md'
    - Deploy OSToy app via YAML: 'app-deployment/4-deploy-yaml.md'
    - Setting up health probe: 'app-deployment/5-health-check.md'
    - Mount AWS EBS storage to app: 'app-deployment/6-storage.md'
    - Inject appliation configs: 'app-deployment/7-inject-configs.md'
    - Implement TLS termination: 'app-deployment/8-networking.md'
    - Scaling your containers: 'app-deployment/9-scaling.md'
    - Challenge & practice!: 'app-deployment/10-challenge-and-exercise.md'

# Theme Configuration
theme:
  name: material
  language: 'en'
  palette:
    primary: black
    accent: red
  font:
    text: Overpass
    code: Overpass Mono
  logo: favicon.ico
  favicon: favicon.ico
docs_dir: rosa-workshop

# Extensions
markdown_extensions:
  - abbr
  - toc:
      permalink: "#"
