# Project Information
site_name: Red Hat OpenShift Service on AWS (ROSA)
site_description: A guided workshop that ranges from application deployment to cluster configuration for ROSA clusters.
site_author: Red Hat

# Nav Menu Definition
nav:
  - Home: index.md
  - Part 1 - ROSA cluster deployment:
    - Setup: 'rosa-deployment/1-account_setup.md'
    - Deploy the cluster: 'rosa-deployment/2-deploy.md'
    - Create an admin user: 'rosa-deployment/3-create_initial_admin.md'
    - Setup an IdP: 'rosa-deployment/4-setup_idp.md'
    - Granting admin rights: 'rosa-deployment/5-grant_admin.md'
    - Accessing your cluster: 'rosa-deployment/6-access_cluster.md'
    - Managing worker nodes: 'rosa-deployment/7-managing_nodes.md'
    - Autoscaling: 'rosa-deployment/8-autoscaling.md'
    - Upgrade the cluster: 'rosa-deployment/9-upgrade.md'
    - Delete the cluster: 'rosa-deployment/12-delete_cluster.md'
    - Obtaining support: 'rosa/13-obtaining_support.md'
  - Part 2 - Application deployment:
    - Deploying hello world app: 'app-deployment/1-deploy-hello-world-using-s2i.md'
    - Deploying sample database: 'app-deployment/2-deploy-sample-db.md'
    - Lab Overview: 'app-deployment/3-lab_overview.md'
    - Deployment: 'app-deployment/4-deployment.md'
    - Health Check: 'app-deployment/5-healthcheck.md'
    - Storage: 'app-deployment/6-storage.md'
    - ConfigMaps, Secrets, Env Var: 'app-deployment/7-confsecenv.md'
    - Networking: 'app-deployment/8-networking.md'
    - Scaling: 'app-deployment/12-scaling.md'
    - Logging: 'app-deployment/9-logging.md'

# Theme Configuration
theme:
  name: material
  language: 'en'
  palette:
    primary: black
    accent: red
  font:
    text: Overpass
    code: Overpass Mono
  logo: favicon.ico
  favicon: favicon.ico
docs_dir: rosa-workshop

# Extensions
markdown_extensions:
  - abbr
  - toc:
      permalink: "#"
