# Project Information
site_name: Red Hat OpenShift Service on AWS (ROSA)
site_description: A guided workshop that ranges from application deployment to cluster configuration for ROSA clusters.
site_author: Red Hat

# Nav Menu Definition
nav:
  - Home: index.md
  - Part 1 - ROSA cluster deployment:
    - Setup: 'rosa-deployment/1-account_setup.md'
    - Deploy the cluster: 'rosa-deployment/2-deploy.md'
    - Create an admin user: 'rosa-deployment/3-create_initial_admin.md'
    - Accessing your cluster: 'rosa-deployment/6-access_cluster.md'
    - Managing worker nodes: 'rosa-deployment/7-managing_nodes.md'
    - Autoscaling: 'rosa-deployment/8-autoscaling.md'
  - Part 2 - Application deployment:
    - Deploying hello world app: 'app-deployment/1-deploy-hello-world-using-s2i.md'
    - Deploying sample database: 'app-deployment/2-deploy-sample-db.md'
    - OSToy app overview: 'app-deployment/3-ostoy-lab-overview.md'
    - Deploy OSToy app via YAML: 'app-deployment/4-deploy-yaml.md'
    - Setting up health probe: 'app-deployment/5-health-check.md'
    - Mount AWS EBS storage to app: 'app-deployment/6-storage.md'
    - Inject appliation configs: 'app-deployment/7-inject-configs.md'
    - Implement TLS termination: 'app-deployment/8-networking.md'
    - Scaling your containers: 'app-deployment/9-scaling.md'
    - Challenge & practice!: 'app-deployment/10-challenge-and-exercise.md'

# Theme Configuration
theme:
  name: material
  language: 'en'
  palette:
    primary: black
    accent: red
  font:
    text: Overpass
    code: Overpass Mono
  logo: favicon.ico
  favicon: favicon.ico
docs_dir: rosa-workshop

# Extensions
markdown_extensions:
  - abbr
  - toc:
      permalink: "#"
