apiVersion: v1
kind: Template
metadata:
  name: rosa-workshop-toolbox-provisioning-template
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: rosa-workshop-toolbox-terminal
    labels:
      app: rosa-workshop-toolbox-terminal
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: rosa-workshop-toolbox-terminal
    template:
      metadata:
        labels:
          app: rosa-workshop-toolbox-terminal
      spec:
        containers:
        - name: rosa-workshop-toolbox
          image: quay.io/nebula0248/rosa-workshop-toolbox:v1.0.0
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
- kind: RoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: ${USERNAME}-admin
  subjects:
    - kind: User
      apiGroup: rbac.authorization.k8s.io
      name: ${USERNAME}
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: admin
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: user-settings-role
    namespace: openshift-console-user-settings
  rules:
    - verbs:
        - get
        - list
        - patch
        - update
        - watch
      apiGroups:
        - ''
      resources:
        - configmaps
- kind: RoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: ${USERNAME}-settings-rolebinding
    namespace: openshift-console-user-settings
  subjects:
    - kind: User
      apiGroup: rbac.authorization.k8s.io
      name: ${USERNAME}
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: user-settings-role
parameters:
- description: Username
  name: USERNAME
  required: true